# Generated by Django 3.1.4 on 2020-12-03 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ques_ans_opt', '0004_auto_20201202_2324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iteration',
            options={'ordering': ['-date_created']},
        ),
    ]
